### ISSUE TITLE
Clarification with clamping of adversarial example in adv_and_watermark.py file

### ISSUE THREAD

**Issue by jvt3112** [ssg-research/conflicts-in-ml-protection-mechanisms#1]
Hi Researchers,

I'd like to draw your attention to the implementation of PGD. Specifically, I have a question regarding the clamping operation for the generation of adversarial examples. In the existing code, it appears that only the perturbation is clamped within the range of [0, 1] before being added to the original sample. However, I believe it is essential to also clamp the resulting adversarial example, i.e., (original sample + perturbation), within the same range. This ensures that the adversarial examples are visually indistinguishable from the original data and adhere to the constraints of the input space.

To support my understanding, I referred to this codebase "https://github.com/MadryLab/mnist_challenge/blob/master/pgd_attack.py" (challenge released by the researchers who proposed PGD).

I would appreciate your clarification on this matter. If my understanding is incorrect, please kindly correct me and provide insight into the reasoning behind the current implementation. On the other hand, if my observation holds true, I would be happy to contribute to the codebase by suggesting a modification to include the clamping operation for adversarial examples.

Thank you for your attention and consideration. I look forward to your response.

Best Regards,
Janvi

**Comment by sebszyller** [comment]
Hi, yes you're correct. One clamp is missing. In the earlier version of the code, it's there. It seems like it got lost while refactoring for the public release of the code.

Feel free to submit a PR. Thanks!
